import os
from google import genai
from dotenv import load_dotenv

load_dotenv()

client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
<style>
  body { font-family: Arial, sans-serif; max-width: 650px; margin: 0 auto; background: #f4f4f4; padding: 20px; }
  .header { background: linear-gradient(135deg, #1a1a2e, #16213e); color: white; padding: 30px; border-radius: 10px 10px 0 0; text-align: center; }
  .header h1 { margin: 0; font-size: 28px; letter-spacing: 2px; }
  .header p { margin: 5px 0 0; color: #a0aec0; font-size: 14px; }
  .content { background: white; padding: 30px; }
  .opening { background: #f7fafc; border-left: 4px solid #4299e1; padding: 15px 20px; margin-bottom: 25px; border-radius: 0 8px 8px 0; }
  .section-title { color: #1a1a2e; font-size: 18px; font-weight: bold; border-bottom: 2px solid #4299e1; padding-bottom: 8px; margin-top: 30px; }
  .trend { background: #f7fafc; border-radius: 8px; padding: 15px 20px; margin: 15px 0; }
  .trend-name { color: #2b6cb0; font-weight: bold; font-size: 16px; }
  .story { background: #fff5f5; border: 1px solid #fed7d7; border-radius: 8px; padding: 20px; margin: 15px 0; }
  .quick-hit { padding: 8px 0; border-bottom: 1px solid #e2e8f0; }
  .quick-hit:last-child { border-bottom: none; }
  .source { color: #718096; font-size: 12px; }
  .closing { background: linear-gradient(135deg, #1a1a2e, #16213e); color: white; padding: 20px 30px; border-radius: 0 0 10px 10px; text-align: center; font-style: italic; }
  .badge { display: inline-block; background: #4299e1; color: white; padding: 3px 10px; border-radius: 20px; font-size: 12px; margin-bottom: 10px; }
</style>
</head>
<body>
<div class="header">
  <div class="badge">AI INTELLIGENCE BRIEF</div>
  <h1>PulseAI</h1>
  <p>Your daily AI news digest — deduplicated, analyzed, delivered</p>
</div>
<div class="content">
CONTENT_PLACEHOLDER
</div>
<div class="closing">
CLOSING_PLACEHOLDER
<br><br>
<small>Generated by PulseAI • Powered by Gemini 2.5 + Pinecone RAG</small>
</div>
</body>
</html>
"""

def generate_newsletter(articles: list[dict], topic: str) -> str:
    articles_text = ""
    for i, article in enumerate(articles[:15], 1):
        articles_text += f"""
Article {i}:
Title: {article['title']}
Summary: {article['summary']}
Source: {article['source']}
Link: {article['link']}
---"""

    fallback = f"No articles found. Use your own knowledge about recent {topic} developments."

    prompt = """You are an expert tech journalist writing a premium AI industry newsletter.

Here are today's news articles about """ + topic + """:

""" + (articles_text if articles_text else fallback) + """

Write the newsletter content as HTML snippets (no full HTML document, just the inner content).

Return exactly two sections separated by the text ---CLOSING---

SECTION 1: The main content HTML including:
- An opening div with class "opening" containing 2-3 sentence executive summary
- A div with class "section-title" containing "📈 TOP 3 TRENDS"
- Three divs with class "trend", each containing a div with class "trend-name" for the trend name, a p tag for analysis, and a p tag with <strong>Why it matters:</strong>
- A div with class "section-title" containing "🗞️ STORY OF THE DAY"  
- A div with class "story" containing 4-5 sentences
- A div with class "section-title" containing "⚡ QUICK HITS"
- Five divs with class "quick-hit" each with a bullet point and span with class "source" for the source

---CLOSING---

SECTION 2: One sharp closing insight sentence (plain text only, no HTML tags)

Return ONLY the HTML content and closing text. No markdown, no backticks, no explanation."""

    response = client.models.generate_content(
        model="models/gemini-2.5-flash",
        contents=prompt
    )

    if not response or not response.text:
        return "<p>Newsletter generation failed. Please try again.</p>"

    parts = response.text.split("---CLOSING---")
    content = parts[0].strip() if len(parts) > 0 else "<p>No content generated.</p>"
    closing = parts[1].strip() if len(parts) > 1 else "The future of AI is being written today."

    return HTML_TEMPLATE.replace("CONTENT_PLACEHOLDER", content).replace("CLOSING_PLACEHOLDER", closing)


if __name__ == "__main__":
    from scraper import scrape_articles
    from embedder import store_articles
    print("Scraping articles...")
    articles = scrape_articles("AI")
    print("Deduplicating with Pinecone...")
    unique_articles = store_articles(articles)
    print("Generating newsletter with Gemini...\n")
    newsletter = generate_newsletter(unique_articles, "AI")
    with open("newsletter_output.html", "w") as f:
        f.write(newsletter)
    print("Saved to newsletter_output.html")
    print(newsletter[:300])